export const GET_PACKAGE_FOR_HOME = 'GET_DOCTOR_FOR_HOME';
export const SAVE_PACKAGE_FOR_HOME = 'SAVE_DOCTOR_FOR_HOME';

export const GET_PACKAGE_ASSIGN_DOCTOR = 'GET_PACKAGE_ASSIGN_DOCTOR';
export const SAVE_PACKAGE_ASSIGN_DOCTOR = 'SAVE_PACKAGE_ASSIGN_DOCTOR';

export const SAVE_PACKAGE_NOT_ASSIGN_DOCTOR ='SAVE_PACKAGE_NOT_ASSIGN_DOCTOR';
export const GET_PACKAGE_NOT_ASSIGN_DOCTOR = 'GET_PACKAGE_NOT_ASSIGN_DOCTOR';

export const DOCTOR_ACCEPT_PACKAGE = "DOCTOR_ACCEPT_PACKAGE";
export const DOCTOR_ACCEPT_PACKAGE_SUCCESSFUL = "DOCTOR_ACCEPT_PACKAGE_SUCCESSFUL";

export const DOCTOR_REJECT_PACKAGE_SUCCESSFUL = "DOCTOR_REJECT_PACKAGE_SUCCESSFUL";
export const DOCTOR_REJECT_PACKAGE = "DOCTOR_REJECT_PACKAGE";

export const NOT_ASSIGN_PACKAGE_QUERY = "NOT_ASSIGN_PACKAGE_QUERY";
export const NOT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL = "NOT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL";

export const ASSIGN_PACKAGE_QUERY = "ASSIGN_PACKAGE_QUERY";
export const ASSIGN_PACKAGE_QUERY_SUCCESSFUL = "ASSIGN_PACKAGE_QUERY_SUCCESSFUL";

export const NEXT_NOT_ASSIGN_PACKAGE_QUERY = "NEXT_NOT_ASSIGN_PACKAGE_QUERY";
export const NEXT_NOT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL = "NEXT_NOT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL";

export const NEXT_ASSIGN_PACKAGE_QUERY = "NEXT_ASSIGN_PACKAGE_QUERY";
export const NEXT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL = "NEXT_ASSIGN_PACKAGE_QUERY_SUCCESSFUL";

export const GET_DOCTOR_PACKAGE = "GET_DOCTOR_PACKAGE";
export const GET_DOCTOR_PACKAGE_SUCCESSFUL = "GET_DOCTOR_PACKAGE_SUCCESSFUL";

export const GET_PACKAGE_INFO = "GET_PACKAGE_INFO";
export const GET_PACKAGE_INFO_SUCCESSFUL = "GET_PACKAGE_INFO_SUCCESSFUL";

export const GET_ALL_APPOINTMENT = "GET_ALL_APPOINTMENT";
export const GET_ALL_APPOINTMENT_SUCCESSFUL = "GET_ALL_APPOINTMENT_SUCCESSFUL";

export const GET_PACKAGE_SERVICES = "GET_PACKAGE_SERVICES";
export const GET_PACKAGE_SERVICES_SUCCESSFUL = "GET_PACKAGE_SERVICES_SUCCESSFUL";


export const GET_PACKAGE_APPOINTMENTS = "GET_PACKAGE_APPOINTMENTS";
export const GET_PACKAGE_APPOINTMENTS_SUCCESSFUL = "GET_PACKAGE_APPOINTMENTs_SUCCESSFUL";

export const GET_PACKAGE_STATUS = "GET_PACKAGE_STATUS";
export const GET_PACKAGE_STATUS_SUCCESSFUL = "GET_PACKAGE_STATUS_SUCCESSFUL";

export const ADD_SERVICE_PACKAGE = "ADD_SERVICE_PACKAGE";
export const EDIT_SERVICE_PACKAGE = "EDIT_SERVICE_PACKAGE";
export const DELETE_SERVICE_PACKAGE = "DELETE_SERVICE_PACKAGE";
export const DELETE_SERVICE_PACKAGE_SUCESSFUL = "DELETE_SERVICE_PACKAGE_SUCESSFUL";

export const ADD_APPOINTMENT_PACKAGE = "ADD_APPOINTMENT_PACKAGE";
export const ADD_APPOINTMENT_PACKAGE_SUCCESSFUL = "ADD_APPOINTMENT_PACKAGE_SUCCESSFUL";
export const UPDATE_APPOINTMENT_PACKAGE = "UPDATE_APPOINTMENT_PACKAGE";

export const CHANGE_PACKAGE_STATUS = "CHANGE_PACKAGE_STATUS";


export const UPDATE_PACKAGE = "UPDATE_PACKAGE";



