export const FORGOT_PASSWORD_SEND_MAIL = 'FORGOT_PASSWORD_SEND_MAIL';
export const FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL';
export const FORGOT_PASSWORD_SEND_PASSWORD = 'FORGOT_PASSWORD_SEND_PASSWORD';
export const FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL';
export const CHECK_EMAIL_EXPIRED = 'CHECK_EMAIL_EXPIRED';
export const CHECK_EMAIL_EXPIRED_SUCCESSFUL = 'CHECK_EMAIL_EXPIRED_SUCCESSFUL';