export const GET_FORM = 'GET_FORM';
export const GET_PACKAGE_RESULT_FORM_SUCCESSFUL = 'GET_PACKAGE_RESULT_FORM_SUCCESSFUL';
export const GET_APPOINTMENT_RESULT_FORM_SUCCESSFUL = 'GET_APPOINTMENT_RESULT_FORM_SUCCESSFUL';
