export const GET_DOCTOR_LOGIN = 'GET_DOCTOR_LOGIN';
export const CLEAR_DOCTOR_LOGIN_INFO = 'CLEAR_DOCTOR_LOGIN_INFO';
export const GET_DOCTOR_LOGIN_SUCCESSFUL = 'GET_DOCTOR_LOGIN';

export const GET_APPOINTMENTS_FROM_TO = 'GET_APPOINTMENTS_FROM_TO';
export const GET_APPOINTMENTS_DETAIL = 'GET_APPOINTMENTS_DETAIL';
export const GET_PATIENT_DETAIL = 'GET_PATIENT_DETAIL';
export const GET_APPOINTMENTS_FROM_TO_SUCCESSFUL = 'GET_APPOINTMENTS_FROM_TO_SUCCESSFUL';
export const GET_APPOINTMENTS_DETAIL_SUCCESSFUL = 'GET_APPOINTMENTS_DETAIL_SUCCESSFUL';
export const GET_PATIENT_DETAIL_SUCCESSFUL = 'GET_PATIENT_DETAIL_SUCCESSFUL';
export const RESET_STATE_DETAIL = 'RESET_STATE_DETAIL';
export const GET_DOCTOR_DETAIL = 'GET_DOCTOR_DETAIL';
export const GET_DOCTOR_DETAIL_SUCCESSFUL = 'GET_DOCTOR_DETAIL_SUCCESSFUL';

export const CHANGE_DOCTOR_PASSWORD = 'CHANGE_DOCTOR_PASSWORD';
export const CHANGE_DOCTOR_PASSWORD_SUCCESSFULL = 'CHANGE_DOCTOR_PASSWORD_SUCCESSFULL';

export const REQUEST_NEW_SERVICE = "REQUEST_NEW_SERVICE";

export const DOCTOR_GET_ALL_SERVICE_REQUEST = "DOCTOR_GET_ALL_SERVICE_REQUEST";
export const DOCTOR_GET_ALL_SERVICE_REQUEST_SUCCESSFULLY = "DOCTOR_GET_ALL_SERVICE_REQUEST_SUCCESSFULLY";